dist: xenial
branches:
  only:
    - master
language: csharp
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.eFormCaseTemplateBase.sln
  - dotnet test -v n Microting.eFormCaseTemplateBase.Unit.Tests/Microting.eFormCaseTemplateBase.Unit.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.eFormCaseTemplateBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-casetemplate-base/Microting.eFormCaseTemplateBase/artifacts/Microting.eFormCaseTemplateBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
